version: '3'
services:
  salgu-api-db:
    image: mysql
    container_name: salgu-api-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ~/project/salgu/db-volume/api:/var/lib/mysql
    ports:
      - 3307:3306

  salgu-auth-db:
    image: mysql
    container_name: salgu-auth-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ~/project/salgu/db-volume/auth:/var/lib/mysql
    ports:
      - 3308:3306

  salgu-payment-db:
    image: mysql
    container_name: salgu-payment-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ~/project/salgu/db-volume/payment:/var/lib/mysql
    ports:
      - 3309:3306